import React, { useState, useEffect, useRef } from 'react';
import { View, Text, StyleSheet, TouchableOpacity, ScrollView, ActivityIndicator, useWindowDimensions, Platform } from 'react-native';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { Modal, Portal, Button, Menu, TextInput, Chip, Divider } from 'react-native-paper';
import api from '../../api/client';
import { uploadFile } from '../../api/officeApi';

const PremisesWizardModal = ({ visible, onClose, onSave, initialData = null }) => {
    const { width, height } = useWindowDimensions();
    const isMobile = width < 768;

    // State
    const [step, setStep] = useState(1);
    const [loading, setLoading] = useState(false);
    const [saving, setSaving] = useState(false);
    const [initializing, setInitializing] = useState(true);
    const [uploadingField, setUploadingField] = useState(null);
    const fileInputRef = useRef(null);
    const currentFileField = useRef(null);
    const SERVER_URL = 'http://localhost:5032';

    // Dropdown Data
    const [countries, setCountries] = useState([]);
    const [propertyTypes, setPropertyTypes] = useState([]);
    const [premisesTypes, setPremisesTypes] = useState([]);
    const [areas, setAreas] = useState([]);
    const [regions, setRegions] = useState([]);
    const [regionsLoading, setRegionsLoading] = useState(false);

    // Dropdown Menus Visibility
    const [menus, setMenus] = useState({
        country: false,
        region: false,
        propertyType: false,
        premisesType: false,
        area: false
    });

    // Form Data - Step 1 (Classification)
    const [classification, setClassification] = useState({
        premise_id: null,
        name: '', // Unified name field
        country_id: null,
        country_name: '',
        region: '',
        property_type_id: null,
        property_type_name: '',
        premises_type_id: null,
        premises_type_name: '',
        area_id: null,
        area_name: '',
        status: 'Active'
    });

    // Dynamic Module Data
    const [moduleStructure, setModuleStructure] = useState([]);
    const [dynamicData, setDynamicData] = useState({});
    const [autoGenerated, setAutoGenerated] = useState({});
    const [moduleId, setModuleId] = useState(1); // Premises module usually 1

    const renderDateInput = (fieldKey, value, onDateChange) => {
        if (Platform.OS === 'web') {
            return (props) => (
                <View style={{ flex: 1, paddingRight: 40 }}>
                    <input
                        type="date"
                        value={value || ''}
                        onChange={(e) => onDateChange(e.target.value)}
                        style={{
                            border: 'none',
                            outline: 'none',
                            backgroundColor: 'transparent',
                            width: '100%',
                            height: 38,
                            fontSize: '13px',
                            color: '#1e293b',
                            cursor: 'pointer',
                            fontFamily: 'inherit'
                        }}
                        onClick={(e) => e.target.showPicker && e.target.showPicker()}
                    />
                </View>
            );
        }
        return undefined;
    };

    // Initialization
    useEffect(() => {
        if (visible) {
            setStep(1);
            fetchDropdowns();

            if (initialData && Object.keys(initialData).length > 0) {
                // Map existing data to classification
                setClassification({
                    premise_id: initialData.premise_id || initialData.id || null,
                    name: initialData.premises_name || initialData.name || '',
                    country_id: initialData.country_id || null,
                    country_name: initialData.country || initialData.country_name || '',
                    region: initialData.region || '',
                    property_type_id: initialData.property_type_id || null,
                    property_type_name: initialData.premise_type || initialData.property_type_name || '',
                    premises_type_id: initialData.premises_type_id || null,
                    premises_type_name: initialData.premises_use || initialData.premises_type_name || '',
                    area_id: initialData.area_id || null,
                    area_name: initialData.area || initialData.area_name || '',
                    status: (initialData.status === 'Active' || initialData.is_active === 1) ? 'Active' : 'Inactive'
                });

                // Extract dynamic data
                const baseKeys = ['premise_id', 'premises_name', 'company_id', 'status', 'is_active', 'country_id', 'property_type_id', 'premises_type_id', 'area_id', 'country', 'region', 'premise_type', 'premises_use', 'area', 'created_at', 'updated_at', 'id'];
                const dynamic = {};
                Object.keys(initialData).forEach(key => {
                    if (!baseKeys.includes(key)) dynamic[key] = initialData[key];
                });
                setDynamicData(dynamic);
            } else {
                setClassification({
                    premise_id: null,
                    name: '',
                    country_id: null,
                    country_name: '',
                    region: '',
                    property_type_id: null,
                    property_type_name: '',
                    premises_type_id: null,
                    premises_type_name: '',
                    area_id: null,
                    area_name: '',
                    status: 'Active'
                });
                setDynamicData({});
                setAutoGenerated({});
                setModuleStructure([]);
            }
        }
    }, [visible, initialData]);

    // Fetch dropdowns
    const fetchDropdowns = async () => {
        setInitializing(true);
        try {
            const [cRes, propRes, premRes, areaRes] = await Promise.all([
                api.get('countries').catch(() => ({ data: [] })),
                api.get('property-types').catch(() => ({ data: [] })),
                api.get('premises-types').catch(() => ({ data: [] })),
                api.get('areas').catch(() => ({ data: [] }))
            ]);

            setCountries(cRes.data?.data || (Array.isArray(cRes.data) ? cRes.data : []));
            setPropertyTypes(propRes.data?.data || (Array.isArray(propRes.data) ? propRes.data : []));
            setPremisesTypes(premRes.data?.data || (Array.isArray(premRes.data) ? premRes.data : []));
            setAreas(areaRes.data?.data || (Array.isArray(areaRes.data) ? areaRes.data : []));

        } catch (error) {
            console.error('[PremisesWizardModal] Error fetching dropdowns:', error);
        } finally {
            setInitializing(false);
        }
    };

    // Fetch Module Configuration based on classification
    useEffect(() => {
        if (visible) {
            fetchModuleConfig();
        }
    }, [visible, classification.country_id, classification.property_type_id, classification.premises_type_id, classification.area_id, classification.region]);

    const fetchModuleConfig = async () => {
        setLoading(true);
        try {
            // 1. Get Premises Module Structure
            const secRes = await api.get(`module-builder/${moduleId}/sections`);
            let sections = secRes.data?.data || [];

            const sectionsWithFields = await Promise.all(sections.map(async (sec) => {
                const fRes = await api.get(`module-builder/fields`, { params: { section_id: sec.id } });
                let fields = fRes.data?.data || [];
                return { ...sec, fields };
            }));

            // 2. Fetch Filtered Field IDs
            const params = { module_id: moduleId };
            if (classification.country_id) params.country_id = classification.country_id;
            if (classification.property_type_id) params.property_type_id = classification.property_type_id;
            if (classification.premises_type_id) params.premises_type_id = classification.premises_type_id;
            if (classification.area_id) params.area_id = classification.area_id;
            if (classification.region && classification.region !== 'All') params.region = classification.region;

            const filterRes = await api.get('company-modules/selected-fields', { params });
            const selectedFieldIds = filterRes.data?.data?.selected_field_ids;

            let filteredSections = [];
            if (!selectedFieldIds) {
                // Show all if no matching config
                filteredSections = sectionsWithFields;
            } else {
                filteredSections = sectionsWithFields.map(sec => ({
                    ...sec,
                    fields: sec.fields.filter(f => selectedFieldIds.some(sid => String(sid) === String(f.id)))
                })).filter(s => s.fields.length > 0);
            }

            setModuleStructure(filteredSections);

            // 3. Handle Auto-generated IDs
            const autoFields = filteredSections.flatMap(s => s.fields || []).filter(f => f.field_type === 'auto_generated');
            if (autoFields.length > 0) {
                const results = {};
                for (const f of autoFields) {
                    const fieldKey = f.field_key || `field_${f.id}`;
                    if (!dynamicData[fieldKey]) {
                        try {
                            const res = await api.get('module-builder/preview-id', {
                                params: { module_id: moduleId, field_key: fieldKey }
                            });
                            if (res.data?.success) results[fieldKey] = res.data.data;
                        } catch (e) { console.error(`ID fetch error for ${fieldKey}:`, e); }
                    }
                }
                if (Object.keys(results).length > 0) {
                    setDynamicData(prev => ({ ...prev, ...results }));
                    setAutoGenerated(prev => ({ ...prev, ...results }));
                }
            }
        } catch (error) {
            console.error('[PremisesWizardModal] Error fetching module config:', error);
        } finally {
            setLoading(false);
        }
    };

    // Region fetching
    useEffect(() => {
        const fetchRegions = async () => {
            const cName = classification.country_name;
            if (!cName) { setRegions([]); return; }
            if (cName.toLowerCase() === 'all') {
                setRegions([{ name: 'All', state_code: 'ALL' }]);
                if (!classification.region) setClassification(p => ({ ...p, region: 'All' }));
                return;
            }
            setRegionsLoading(true);
            try {
                let queryCountry = cName;
                if (queryCountry.toLowerCase() === 'uae') queryCountry = 'United Arab Emirates';
                const res = await fetch('https://countriesnow.space/api/v0.1/countries/states', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ country: queryCountry })
                });
                const data = await res.json();
                if (data.data && data.data.states) {
                    setRegions(data.data.states.map(s => ({ name: s.name, state_code: s.state_code })));
                }
            } catch (e) { console.error('Region fetch error:', e); }
            finally { setRegionsLoading(false); }
        };
        if (classification.country_name) fetchRegions();
    }, [classification.country_name]);

    const handleFileSelect = async (event) => {
        const file = event.target.files?.[0];
        const fieldKey = currentFileField.current;
        if (!file || !fieldKey) return;

        setUploadingField(fieldKey);
        const reader = new FileReader();
        reader.onloadend = async () => {
            const base64 = reader.result;
            try {
                const date = new Date();
                const formattedDate = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
                const randomNum = Math.floor(100 + Math.random() * 900);
                const customFileName = `PR ${formattedDate} - ${file.name} - ${randomNum}`;

                const result = await uploadFile({ name: customFileName, content: base64, moduleName: 'Premises' });
                if (result.success) {
                    setDynamicData(p => ({ ...p, [fieldKey]: result.path, [`${fieldKey}_name`]: customFileName }));
                }
            } catch (error) { console.error('File upload failed:', error); }
            finally {
                setUploadingField(null);
                if (fileInputRef.current) fileInputRef.current.value = '';
            }
        };
        reader.readAsDataURL(file);
    };

    const triggerFilePicker = (fieldKey) => {
        currentFileField.current = fieldKey;
        if (fileInputRef.current) fileInputRef.current.click();
    };

    const handleNext = () => setStep(prev => Math.min(prev + 1, 1 + moduleStructure.length));
    const handleBack = () => { if (step > 1) setStep(prev => prev - 1); else onClose(); };

    const handleSaveForm = async () => {
        setSaving(true);
        try {
            const nameFallback = `${classification.premises_type_name || 'Premise'} - ${classification.area_name || classification.region || 'New'}`;
            const addressFallback = classification.area_name ? `${classification.area_name}, ${classification.region}` : (classification.region || 'Address set via system');

            const payload = {
                ...classification,
                ...dynamicData,
                premises_name: (classification.name || dynamicData.premises_name || dynamicData.name || nameFallback).trim(),
                building_name: classification.building_name || dynamicData.building_name || classification.area_name || 'Main Building',
                city: classification.city || dynamicData.city || classification.region || classification.area_name || 'City',
                full_address: (classification.full_address || dynamicData.full_address || addressFallback).trim(),
                premise_type: classification.property_type_name === 'Rental' ? 'RENTED' : (classification.property_type_name === 'Owned' ? 'OWNED' : classification.property_type_name),
                premises_use: (classification.premises_type_name || '').toUpperCase(),
                country: classification.country_name,
                area: classification.area_name
            };
            await onSave(payload);
        } catch (error) {
            console.error('Save error:', error);
        } finally {
            setSaving(false);
        }
    };

    const totalSteps = 1 + moduleStructure.length;
    const toggleMenu = (key, val) => setMenus(prev => ({ ...prev, [key]: val }));

    const renderDynamicSection = (stepIndex) => {
        const section = moduleStructure[stepIndex - 2];
        if (!section) return null;

        const parseFileConfig = (str) => {
            if (str && str.startsWith("JSON:")) {
                try { return JSON.parse(str.replace("JSON:", "")); } catch (e) { return {}; }
            }
            return {};
        };

        return (
            <View style={styles.stepContent}>
                <View style={styles.dynamicCard}>
                    <View style={styles.sectionHeaderCard}>
                        <Text style={styles.sectionHeaderTitle}>{stepIndex}. {section.name}</Text>
                    </View>
                    <View style={styles.cardBody}>
                        {Platform.OS === 'web' && (
                            <input type="file" ref={fileInputRef} style={{ display: 'none' }} onChange={handleFileSelect} />
                        )}
                        <View style={styles.fieldsGrid}>
                            {(section.fields || []).map(field => {
                                const fieldName = field.label || field.field_label || field.name || 'Field';
                                const fieldKey = field.field_key || `field_${field.id}`;
                                const isFile = field.field_type === 'file' || fieldName.toLowerCase().includes('document');
                                const isDate = field.field_type === 'date' || fieldName.toLowerCase().includes('date');

                                if (isFile) {
                                    const filePath = dynamicData[fieldKey];
                                    const fileName = dynamicData[`${fieldKey}_name`] || (filePath ? filePath.split('/').pop() : '');
                                    const config = parseFileConfig(field.placeholder);
                                    const hasAnyExtra = config.expiry || config.issueDate || config.startDate || config.endDate || config.policyNo || config.coverageType;

                                    return (
                                        <View key={field.id} style={[styles.dynamicField, hasAnyExtra && { width: '100%' }]}>
                                            <Text style={styles.inputLabel}>{fieldName}</Text>
                                            <View style={hasAnyExtra ? { flexDirection: 'row', gap: 16, alignItems: 'flex-start' } : null}>
                                                <View style={hasAnyExtra ? { flex: 1.5 } : null}>
                                                    {filePath ? (
                                                        <View style={styles.fileCard}>
                                                            <View style={{ flexDirection: 'row', alignItems: 'center', gap: 12 }}>
                                                                <MaterialCommunityIcons name="file-document-outline" size={24} color="#3b82f6" />
                                                                <View style={{ flex: 1 }}>
                                                                    <Text style={styles.fileName} numberOfLines={1}>{fileName}</Text>
                                                                    <Text style={styles.fileSub}>Uploaded Successfully</Text>
                                                                </View>
                                                                <TouchableOpacity onPress={() => triggerFilePicker(fieldKey)}><MaterialCommunityIcons name="pencil-outline" size={20} color="#64748b" /></TouchableOpacity>
                                                            </View>
                                                        </View>
                                                    ) : (
                                                        <TouchableOpacity style={[styles.uploadBox, uploadingField === fieldKey && { opacity: 0.6 }]} onPress={() => triggerFilePicker(fieldKey)} disabled={uploadingField === fieldKey}>
                                                            {uploadingField === fieldKey ? <ActivityIndicator color="#3b82f6" /> : <><MaterialCommunityIcons name="cloud-upload-outline" size={28} color="#94a3b8" /><Text style={styles.uploadText}>Upload {fieldName}</Text></>}
                                                        </TouchableOpacity>
                                                    )}
                                                </View>

                                                {hasAnyExtra && (
                                                    <View style={{ flex: 3, flexDirection: 'row', flexWrap: 'wrap', gap: 12 }}>
                                                        {config.policyNo && (
                                                            <View style={{ width: '48%' }}>
                                                                <Text style={[styles.inputLabel, { fontSize: 11, marginBottom: 4 }]}>Policy No.</Text>
                                                                <TextInput mode="outlined" dense value={dynamicData[`${fieldKey}_policy_no`] || ''} onChangeText={(t) => setDynamicData(p => ({ ...p, [`${fieldKey}_policy_no`]: t }))} style={{ height: 40, fontSize: 13, backgroundColor: '#fff' }} outlineStyle={{ borderRadius: 8 }} />
                                                            </View>
                                                        )}
                                                        {config.coverageType && (
                                                            <View style={{ width: '48%' }}>
                                                                <Text style={[styles.inputLabel, { fontSize: 11, marginBottom: 4 }]}>Coverage Type</Text>
                                                                <TextInput mode="outlined" dense value={dynamicData[`${fieldKey}_coverage_type`] || ''} onChangeText={(t) => setDynamicData(p => ({ ...p, [`${fieldKey}_coverage_type`]: t }))} style={{ height: 40, fontSize: 13, backgroundColor: '#fff' }} outlineStyle={{ borderRadius: 8 }} />
                                                            </View>
                                                        )}
                                                        {config.issueDate && (
                                                            <View style={{ width: '31%' }}>
                                                                <Text style={[styles.inputLabel, { fontSize: 11, marginBottom: 4 }]}>Issue Date</Text>
                                                                <TextInput mode="outlined" dense value={dynamicData[`${fieldKey}_issue_date`] || ''} onChangeText={(t) => setDynamicData(p => ({ ...p, [`${fieldKey}_issue_date`]: t }))} style={{ height: 40, fontSize: 13, backgroundColor: '#fff' }} outlineStyle={{ borderRadius: 8 }} right={<TextInput.Icon icon="calendar" size={16} />} render={renderDateInput(`${fieldKey}_issue_date`, dynamicData[`${fieldKey}_issue_date`], (val) => setDynamicData(p => ({ ...p, [`${fieldKey}_issue_date`]: val })))} />
                                                            </View>
                                                        )}
                                                        {config.startDate && (
                                                            <View style={{ width: '31%' }}>
                                                                <Text style={[styles.inputLabel, { fontSize: 11, marginBottom: 4 }]}>Start Date</Text>
                                                                <TextInput mode="outlined" dense value={dynamicData[`${fieldKey}_start_date`] || ''} onChangeText={(t) => setDynamicData(p => ({ ...p, [`${fieldKey}_start_date`]: t }))} style={{ height: 40, fontSize: 13, backgroundColor: '#fff' }} outlineStyle={{ borderRadius: 8 }} right={<TextInput.Icon icon="calendar" size={16} />} render={renderDateInput(`${fieldKey}_start_date`, dynamicData[`${fieldKey}_start_date`], (val) => setDynamicData(p => ({ ...p, [`${fieldKey}_start_date`]: val })))} />
                                                            </View>
                                                        )}
                                                        {config.endDate && (
                                                            <View style={{ width: '31%' }}>
                                                                <Text style={[styles.inputLabel, { fontSize: 11, marginBottom: 4 }]}>End Date</Text>
                                                                <TextInput mode="outlined" dense value={dynamicData[`${fieldKey}_end_date`] || ''} onChangeText={(t) => setDynamicData(p => ({ ...p, [`${fieldKey}_end_date`]: t }))} style={{ height: 40, fontSize: 13, backgroundColor: '#fff' }} outlineStyle={{ borderRadius: 8 }} right={<TextInput.Icon icon="calendar" size={16} />} render={renderDateInput(`${fieldKey}_end_date`, dynamicData[`${fieldKey}_end_date`], (val) => setDynamicData(p => ({ ...p, [`${fieldKey}_end_date`]: val })))} />
                                                            </View>
                                                        )}
                                                        {config.expiry && (
                                                            <View style={{ width: '31%' }}>
                                                                <Text style={[styles.inputLabel, { fontSize: 11, marginBottom: 4 }]}>Expiry Date</Text>
                                                                <TextInput mode="outlined" dense value={dynamicData[`${fieldKey}_expiry_date`] || ''} onChangeText={(t) => setDynamicData(p => ({ ...p, [`${fieldKey}_expiry_date`]: t }))} style={{ height: 40, fontSize: 13, backgroundColor: '#fff' }} outlineStyle={{ borderRadius: 8 }} right={<TextInput.Icon icon="calendar" size={16} />} render={renderDateInput(`${fieldKey}_expiry_date`, dynamicData[`${fieldKey}_expiry_date`], (val) => setDynamicData(p => ({ ...p, [`${fieldKey}_expiry_date`]: val })))} />
                                                            </View>
                                                        )}
                                                        {config.reminder && (
                                                            <View style={{ width: '100%', marginTop: 8 }}>
                                                                <Text style={[styles.inputLabel, { fontSize: 11, marginBottom: 4 }]}>Reminder (Days before expiry)</Text>
                                                                <View style={{ flexDirection: 'row', gap: 8 }}>
                                                                    {[30, 60, 90].map(days => (
                                                                        <Chip
                                                                            key={days}
                                                                            selected={dynamicData[`${fieldKey}_reminder`] === String(days)}
                                                                            onPress={() => setDynamicData(p => ({ ...p, [`${fieldKey}_reminder`]: String(days) }))}
                                                                            style={{ height: 32 }}
                                                                            textStyle={{ fontSize: 12 }}
                                                                        >
                                                                            {days} Days
                                                                        </Chip>
                                                                    ))}
                                                                </View>
                                                            </View>
                                                        )}
                                                    </View>
                                                )}
                                            </View>
                                        </View>
                                    );
                                }

                                return (
                                    <View key={field.id} style={styles.dynamicField}>
                                        <Text style={styles.inputLabel}>{fieldName}</Text>
                                        <TextInput
                                            mode="outlined"
                                            placeholder={field.field_type === 'auto_generated' ? '[SYSTEM GENERATED]' : `Enter ${fieldName.toLowerCase()}`}
                                            value={dynamicData[fieldKey] || ''}
                                            onChangeText={(text) => setDynamicData(p => ({ ...p, [fieldKey]: text }))}
                                            editable={field.field_type !== 'auto_generated'}
                                            style={[styles.headerInput, field.field_type === 'auto_generated' && { backgroundColor: '#f8fafc' }]}
                                            outlineColor="#e2e8f0" activeOutlineColor="#3b82f6" theme={{ roundness: 8 }}
                                            right={field.field_type === 'auto_generated' ? <TextInput.Icon icon="lock" color="#94a3b8" /> : isDate ? <TextInput.Icon icon="calendar" color="#94a3b8" /> : <TextInput.Icon icon="pencil-outline" color="#94a3b8" />}
                                            render={isDate ? renderDateInput(fieldKey, dynamicData[fieldKey], (val) => setDynamicData(p => ({ ...p, [fieldKey]: val }))) : undefined}
                                        />
                                    </View>
                                );
                            })}
                        </View>
                    </View>
                </View>
            </View>
        );
    };

    return (
        <Portal>
            <Modal visible={visible} onDismiss={onClose} contentContainerStyle={styles.container}>
                <View style={styles.modalHeader}>
                    <View>
                        <Text style={styles.modalTitle}>Step {step}: {step === 1 ? 'General Information' : (moduleStructure[step - 2]?.name || 'Details')}</Text>
                    </View>
                    <TouchableOpacity onPress={onClose} style={styles.closeBtn}><MaterialCommunityIcons name="close" size={24} color="#1e293b" /></TouchableOpacity>
                </View>

                {/* Stepper */}
                <View style={styles.stepperContainer}>
                    <View style={styles.stepperWrapper}>
                        {Array.from({ length: totalSteps }).map((_, i) => {
                            const stepNum = i + 1;
                            const isActive = step === stepNum;
                            const isCompleted = step > stepNum;
                            return (
                                <View key={stepNum} style={styles.stepItemWrapper}>
                                    <View style={[styles.stepIndicator, (isActive || isCompleted) && styles.stepIndicatorActive]}>
                                        <Text style={[styles.stepIndicatorText, (isActive || isCompleted) && styles.stepIndicatorTextActive]}>{stepNum}</Text>
                                    </View>
                                    {i < totalSteps - 1 && <View style={[styles.stepLine, isCompleted && styles.stepLineActive]} />}
                                </View>
                            );
                        })}
                    </View>
                </View>

                {initializing ? (
                    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center', padding: 40 }}><ActivityIndicator size="large" color="#3b82f6" /><Text style={{ marginTop: 16, color: '#64748b' }}>Refreshing data...</Text></View>
                ) : (
                    <>
                        <ScrollView style={{ flex: 1 }}>
                            {step === 1 && (
                                <View style={styles.fixedHeader}>
                                    <View style={styles.sectionHeader}><Text style={styles.sectionTitle}>{step}. General Information</Text></View>
                                    <View style={styles.headerFormContent}>
                                        <View style={styles.headerField}>
                                            <Text style={styles.inputLabel}>Country</Text>
                                            <Menu visible={menus.country} onDismiss={() => toggleMenu('country', false)} anchor={
                                                <TouchableOpacity onPress={() => toggleMenu('country', true)} activeOpacity={0.7}><View pointerEvents="none"><TextInput mode="outlined" placeholder="Country" value={classification.country_name} editable={false} style={styles.headerInput} outlineColor="#cbd5e1" right={<TextInput.Icon icon="chevron-down" size={20} />} /></View></TouchableOpacity>
                                            } contentStyle={styles.menuContent}>
                                                <ScrollView style={{ maxHeight: 200, width: 220 }}>
                                                    {countries.length === 0 ? <Menu.Item title="No countries found" disabled /> :
                                                        countries.map(c => <Menu.Item key={c.id} onPress={() => { toggleMenu('country', false); setClassification(p => ({ ...p, country_id: c.id, country_name: c.country_name || c.name })); }} title={c.country_name || c.name} titleStyle={styles.menuItemLabel} />)
                                                    }
                                                </ScrollView>
                                            </Menu>
                                        </View>

                                        <View style={styles.headerField}>
                                            <Text style={styles.inputLabel}>Region</Text>
                                            <Menu visible={menus.region} onDismiss={() => toggleMenu('region', false)} anchor={
                                                <TouchableOpacity onPress={() => toggleMenu('region', true)} activeOpacity={0.7} disabled={!classification.country_id}><View pointerEvents="none"><TextInput mode="outlined" placeholder="Region" value={classification.region} editable={false} style={styles.headerInput} outlineColor="#cbd5e1" right={<TextInput.Icon icon="chevron-down" size={20} />} /></View></TouchableOpacity>
                                            } contentStyle={styles.menuContent}>
                                                <ScrollView style={{ maxHeight: 200, width: 220 }}>
                                                    {regionsLoading ? <View style={{ padding: 10 }}><ActivityIndicator size="small" color="#3b82f6" /></View> :
                                                        (regions.length === 0 ? <Menu.Item title="No regions found" disabled /> :
                                                            regions.map((r, i) => <Menu.Item key={i} onPress={() => { toggleMenu('region', false); setClassification(p => ({ ...p, region: r.name })); }} title={r.name} titleStyle={styles.menuItemLabel} />)
                                                        )
                                                    }
                                                </ScrollView>
                                            </Menu>
                                        </View>

                                        <View style={styles.headerField}>
                                            <Text style={styles.inputLabel}>Property Type</Text>
                                            <Menu visible={menus.propertyType} onDismiss={() => toggleMenu('propertyType', false)} anchor={
                                                <TouchableOpacity onPress={() => toggleMenu('propertyType', true)} activeOpacity={0.7}><View pointerEvents="none"><TextInput mode="outlined" placeholder="Property Type" value={classification.property_type_name} editable={false} style={styles.headerInput} outlineColor="#cbd5e1" right={<TextInput.Icon icon="chevron-down" size={20} />} /></View></TouchableOpacity>
                                            } contentStyle={styles.menuContent}>
                                                <ScrollView style={{ maxHeight: 200, width: 220 }}>
                                                    {propertyTypes.length === 0 ? <Menu.Item title="No types found" disabled /> :
                                                        propertyTypes.map(t => <Menu.Item key={t.id} onPress={() => { toggleMenu('propertyType', false); setClassification(p => ({ ...p, property_type_id: t.id, property_type_name: t.name })); }} title={t.name} titleStyle={styles.menuItemLabel} />)
                                                    }
                                                </ScrollView>
                                            </Menu>
                                        </View>

                                        <View style={styles.headerField}>
                                            <Text style={styles.inputLabel}>Premises Type</Text>
                                            <Menu visible={menus.premisesType} onDismiss={() => toggleMenu('premisesType', false)} anchor={
                                                <TouchableOpacity onPress={() => toggleMenu('premisesType', true)} activeOpacity={0.7}><View pointerEvents="none"><TextInput mode="outlined" placeholder="Type" value={classification.premises_type_name} editable={false} style={styles.headerInput} outlineColor="#cbd5e1" right={<TextInput.Icon icon="chevron-down" size={20} />} /></View></TouchableOpacity>
                                            } contentStyle={styles.menuContent}>
                                                <ScrollView style={{ maxHeight: 200, width: 220 }}>
                                                    {premisesTypes.length === 0 ? <Menu.Item title="No types found" disabled /> :
                                                        premisesTypes.map(t => <Menu.Item key={t.id} onPress={() => { toggleMenu('premisesType', false); setClassification(p => ({ ...p, premises_type_id: t.id, premises_type_name: t.type_name })); }} title={t.type_name} titleStyle={styles.menuItemLabel} />)
                                                    }
                                                </ScrollView>
                                            </Menu>
                                        </View>

                                        <View style={styles.headerField}>
                                            <Text style={styles.inputLabel}>Area</Text>
                                            <Menu visible={menus.area} onDismiss={() => toggleMenu('area', false)} anchor={
                                                <TouchableOpacity onPress={() => toggleMenu('area', true)} activeOpacity={0.7}><View pointerEvents="none"><TextInput mode="outlined" placeholder="Area" value={classification.area_name} editable={false} style={styles.headerInput} outlineColor="#cbd5e1" right={<TextInput.Icon icon="chevron-down" size={20} />} /></View></TouchableOpacity>
                                            } contentStyle={styles.menuContent}>
                                                <ScrollView style={{ maxHeight: 200, width: 220 }}>
                                                    {areas.length === 0 ? <Menu.Item title="No areas found" disabled /> :
                                                        areas.map(a => <Menu.Item key={a.id} onPress={() => { toggleMenu('area', false); setClassification(p => ({ ...p, area_id: a.id, area_name: a.name })); }} title={a.name} titleStyle={styles.menuItemLabel} />)
                                                    }
                                                </ScrollView>
                                            </Menu>
                                        </View>

                                        <View style={styles.statusField}>
                                            <Text style={styles.inputLabel}>Status</Text>
                                            <View style={styles.statusPill}>
                                                <Text style={styles.statusPillText}>Active</Text>
                                            </View>
                                            <Text style={styles.systemSetText}>System Set</Text>
                                        </View>
                                    </View>
                                </View>
                            )}
                            {step >= 2 && renderDynamicSection(step)}
                        </ScrollView>
                        <View style={styles.modalFooter}>
                            <TouchableOpacity onPress={onClose} style={styles.cancelBtn}>
                                <MaterialCommunityIcons name="close" size={20} color="#ef4444" />
                                <Text style={styles.cancelBtnText}>Cancel</Text>
                            </TouchableOpacity>

                            <View style={{ flexDirection: 'row', gap: 12 }}>
                                <TouchableOpacity
                                    onPress={handleBack}
                                    style={[styles.backBtn, step === 1 && { opacity: 0.5 }]}
                                    disabled={step === 1}
                                >
                                    <MaterialCommunityIcons name="arrow-left" size={20} color="#94a3b8" />
                                    <Text style={styles.backBtnText}>Back</Text>
                                </TouchableOpacity>

                                {step < totalSteps && totalSteps > 1 ? (
                                    <TouchableOpacity onPress={handleNext} style={styles.nextBtn}>
                                        <Text style={styles.nextBtnText}>Next</Text>
                                        <MaterialCommunityIcons name="arrow-right" size={20} color="white" />
                                    </TouchableOpacity>
                                ) : (
                                    <TouchableOpacity onPress={handleSaveForm} style={[styles.saveBtn, { backgroundColor: '#10b981' }]} disabled={loading || saving}>
                                        {loading || saving ? <ActivityIndicator color="white" /> : <><Text style={styles.saveBtnText}>Save Premises</Text><MaterialCommunityIcons name="check" size={20} color="white" /></>}
                                    </TouchableOpacity>
                                )}
                            </View>
                        </View>
                    </>
                )}
            </Modal>
        </Portal>
    );
};

const styles = StyleSheet.create({
    container: { backgroundColor: 'white', alignSelf: 'center', width: '95%', maxWidth: 1100, maxHeight: '98%', borderRadius: 12, overflow: 'hidden' },
    modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 16, paddingHorizontal: 24, borderBottomWidth: 1, borderBottomColor: '#f1f5f9', backgroundColor: '#fff' },
    modalTitle: { fontSize: 13, fontWeight: '700', color: '#64748b' },
    closeBtn: { padding: 4 },
    stepperContainer: { backgroundColor: '#fff', borderBottomWidth: 1, borderBottomColor: '#f1f5f9' },
    stepperWrapper: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', paddingVertical: 24, paddingHorizontal: 40 },
    stepItemWrapper: { flexDirection: 'row', alignItems: 'center' },
    stepIndicator: { width: 28, height: 28, borderRadius: 14, backgroundColor: '#f1f5f9', justifyContent: 'center', alignItems: 'center', zIndex: 10 },
    stepIndicatorActive: { backgroundColor: '#3b82f6' },
    stepIndicatorText: { color: '#94a3b8', fontSize: 13, fontWeight: '700' },
    stepIndicatorTextActive: { color: 'white' },
    stepLine: { height: 2, width: 80, backgroundColor: '#f1f5f9', marginHorizontal: -4 },
    stepLineActive: { backgroundColor: '#3b82f6' },
    fixedHeader: { backgroundColor: '#fff' },
    sectionHeader: { backgroundColor: 'rgb(108, 122, 224)', paddingVertical: 12, paddingHorizontal: 24 },
    sectionTitle: { fontWeight: '800', color: '#fff', fontSize: 18 },
    headerFormContent: { flexDirection: 'row', padding: 24, paddingVertical: 32, gap: 16, flexWrap: 'wrap' },
    headerField: { flex: 1, minWidth: 160 },
    inputLabel: { fontSize: 13, fontWeight: '600', color: '#1e293b', marginBottom: 10 },
    headerInput: { backgroundColor: '#fff', height: 48, fontSize: 14 },
    statusField: { minWidth: 100, marginLeft: 16, alignItems: 'center' },
    statusPill: { backgroundColor: '#eff6ff', borderRadius: 8, paddingHorizontal: 16, paddingVertical: 10, borderWidth: 1, borderColor: '#dbeafe' },
    statusPillText: { color: '#2563eb', fontWeight: '700', fontSize: 13 },
    systemSetText: { fontSize: 10, color: '#94a3b8', marginTop: 6 },
    menuItemLabel: { fontSize: 14, color: '#1e293b', fontWeight: '500' },
    stepContent: { padding: 24 },
    dynamicCard: { backgroundColor: '#fff', borderRadius: 12, borderWidth: 1, borderColor: '#e2e8f0', overflow: 'hidden' },
    sectionHeaderCard: { backgroundColor: 'rgb(108, 122, 224)', paddingVertical: 14, paddingHorizontal: 24 },
    sectionHeaderTitle: { fontWeight: '800', color: '#fff', fontSize: 18, textTransform: 'uppercase' },
    cardBody: { padding: 24 },
    fieldsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 20 },
    dynamicField: { width: '47%', marginBottom: 10 },
    fileCard: { backgroundColor: '#f8fafc', borderRadius: 12, padding: 12, borderWidth: 1, borderColor: '#e2e8f0', height: 64, justifyContent: 'center' },
    fileName: { fontSize: 13, fontWeight: '700', color: '#1e293b' },
    fileSub: { fontSize: 11, color: '#64748b' },
    uploadBox: { height: 100, borderRadius: 12, borderWidth: 2, borderColor: '#cbd5e1', borderStyle: 'dashed', justifyContent: 'center', alignItems: 'center', backgroundColor: '#f8fafc' },
    uploadText: { marginTop: 8, fontSize: 13, color: '#475569', fontWeight: '700' },
    modalFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 24, borderTopWidth: 1, borderTopColor: '#f1f5f9', backgroundColor: '#fff' },
    cancelBtn: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 20, paddingVertical: 12, borderRadius: 8, borderWidth: 1, borderColor: '#fee2e2', gap: 8 },
    cancelBtnText: { color: '#ef4444', fontWeight: '800', fontSize: 14 },
    backBtn: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 20, paddingVertical: 12, borderRadius: 8, borderWidth: 1, borderColor: '#e2e8f0', gap: 8 },
    backBtnText: { color: '#94a3b8', fontWeight: '800', fontSize: 14 },
    nextBtn: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#3b82f6', paddingHorizontal: 32, paddingVertical: 12, borderRadius: 8, gap: 10 },
    nextBtnText: { color: 'white', fontWeight: '800', fontSize: 14 },
    saveBtn: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 32, paddingVertical: 12, borderRadius: 8, gap: 10 },
    saveBtnText: { color: 'white', fontWeight: '800', fontSize: 14 },
    menuContent: { backgroundColor: 'white', borderRadius: 8, elevation: 8 }
});

export default PremisesWizardModal;
