import React, { useState, useEffect, useRef } from 'react';
import { View, ScrollView, StyleSheet, TouchableOpacity, ActivityIndicator, Platform } from 'react-native';
import { Modal, Portal, Button, Menu, TextInput, Chip, Divider, Dialog, Text, Card, Switch, RadioButton } from 'react-native-paper';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import api from '../../api/client';
import { uploadFile } from '../../api/officeApi';
import AlertDialog from '../AlertDialog';

const VehicleWizardModal = ({ visible, onClose, onSave, initialData }) => {
    const [step, setStep] = useState(1);
    const [loading, setLoading] = useState(false);
    const [saving, setSaving] = useState(false);
    const [initializing, setInitializing] = useState(true);
    const fileInputRef = useRef(null);
    const currentFileField = useRef(null);
    const [uploadingField, setUploadingField] = useState(null);

    // Dropdown Data
    const [companies, setCompanies] = useState([]);
    const [countries, setCountries] = useState([]);
    const [propertyTypes, setPropertyTypes] = useState([]);
    const [premisesTypes, setPremisesTypes] = useState([]);
    const [areas, setAreas] = useState([]);
    const [vehicleUsages, setVehicleUsages] = useState([]);
    const [vehicleCategories, setVehicleCategories] = useState([]);
    const [regions, setRegions] = useState([]);
    const [regionsLoading, setRegionsLoading] = useState(false);

    // Dropdown Menus Visibility
    const [menus, setMenus] = useState({
        company: false,
        country: false,
        region: false,
        premisesType: false,
        area: false
    });
    const [activeDynamicMenu, setActiveDynamicMenu] = useState(null);

    // Form Data - Step 1
    const [classification, setClassification] = useState({
        vehicle_id: null,
        company_id: null,
        company_name: '',
        vehicle_name: '',
        license_plate: '',
        type: '',
        driver: '',
        vehicle_usage_id: null,
        country_id: null,
        region: '',
        status: 'Active',
        country_name: '',
        premises_type_name: ''
    });

    // Dynamic Module Data
    const [moduleStructure, setModuleStructure] = useState([]);
    const [dynamicData, setDynamicData] = useState({});
    const [autoGenerated, setAutoGenerated] = useState({});
    const [moduleId, setModuleId] = useState(null);
    const [alertDialog, setAlertDialog] = useState({ visible: false, title: '', message: '' });

    const renderDateInput = (fieldKey, value, onDateChange) => {
        if (Platform.OS === 'web') {
            return (props) => (
                <View style={{ flex: 1, paddingRight: 40 }}>
                    <input
                        type="date"
                        value={value || ''}
                        onChange={(e) => onDateChange(e.target.value)}
                        style={{
                            border: 'none',
                            outline: 'none',
                            backgroundColor: 'transparent',
                            width: '100%',
                            height: 38,
                            fontSize: '13px',
                            color: '#1e293b',
                            cursor: 'pointer',
                            fontFamily: 'inherit'
                        }}
                        onClick={(e) => e.target.showPicker && e.target.showPicker()}
                    />
                </View>
            );
        }
        return undefined;
    };

    // Initialization
    useEffect(() => {
        if (visible) {
            setStep(1);
            setInitializing(true);
            fetchDropdowns();
            fetchModuleConfig();

            if (initialData && Object.keys(initialData).length > 0) {
                setClassification({
                    vehicle_id: initialData.vehicle_id || null,
                    company_id: initialData.company_id || null,
                    company_name: initialData.company_name || '',
                    vehicle_name: initialData.vehicle_name || '',
                    license_plate: initialData.license_plate || '',
                    type: initialData.type || '',
                    driver: initialData.driver || '',
                    vehicle_usage_id: initialData.vehicle_usage_id || null,
                    country_id: initialData.country_id || null,
                    region: initialData.region || '',
                    status: initialData.status || 'Active',
                    country_name: initialData.country_name || '',
                    premises_type_name: initialData.premises_type_name || ''
                });

                const baseKeys = [
                    // Primary vehicle table columns
                    'vehicle_id', 'company_id', 'vehicle_name', 'license_plate', 'type', 'driver',
                    'status', 'is_active', 'country_id', 'property_type_id', 'premises_type_id',
                    'vehicle_usage_id', 'area_id', 'vehicle_category_id', 'region', 'vehicle_usage',
                    'created_at', 'updated_at', 'image_path',
                    // JOIN aliases from getVehicles query
                    'country_name', 'country', 'area', 'area_name', 'property_type_name',
                    'vehicle_type_name', 'vehicle_usage_name', 'premises_type_name',
                    'vehicle_category_name', 'company_name'
                ];
                const dynamic = {};
                Object.keys(initialData).forEach(key => {
                    dynamic[key] = initialData[key];
                });
                setDynamicData(dynamic);
            } else {
                setClassification({
                    company_id: null,
                    company_name: '',
                    vehicle_usage_id: null,
                    country_id: null,
                    region: '',
                    status: 'Active',
                    country_name: '',
                    premises_type_name: ''
                });
                setDynamicData({});
                setAutoGenerated({});
                setModuleStructure([]);
            }
        }
    }, [visible, initialData]);

    useEffect(() => {
        if (visible && (classification.country_id || classification.vehicle_usage_id || classification.region)) {
            fetchModuleConfig();
        }
    }, [classification.country_id, classification.vehicle_usage_id, classification.region]);

    useEffect(() => {
        if (classification.country_id) {
            fetchRegions(classification.country_id);
        } else {
            setRegions([]);
        }
    }, [classification.country_id]);

    const fetchDropdowns = async () => {
        try {
            const [cRes, propRes, premRes, areaRes, usageRes, vCatRes, compRes] = await Promise.all([
                api.get('countries'),
                api.get('property-types'),
                api.get('premises-types'),
                api.get('areas'),
                api.get('vehicle-usage'),
                api.get('vehicle-categories'),
                api.get('companies')
            ]);

            if (cRes.data?.success) setCountries(cRes.data.data);
            if (propRes.data?.success) setPropertyTypes(propRes.data.data);
            if (premRes.data?.success) setPremisesTypes(premRes.data.data);
            if (areaRes.data?.success) setAreas(areaRes.data.data || areaRes.data);
            if (usageRes.data?.success) setVehicleUsages(usageRes.data.data);
            if (vCatRes.data?.success) setVehicleCategories(vCatRes.data.data);
            if (compRes.data?.success) setCompanies(compRes.data.data);

        } catch (error) {
            console.error('Error fetching dropdowns:', error);
        }
    };

    const fetchRegions = async (countryId) => {
        if (!countryId) return;
        setRegionsLoading(true);
        try {
            // Find the country name correctly from the list
            const countryObj = countries.find(c => String(c.id) === String(countryId));
            const countryName = countryObj?.country_name || countryObj?.name || classification.country_name || '';

            if (countryName.toLowerCase().includes('india')) {
                const res = await fetch('https://countriesnow.space/api/v0.1/countries/states', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ country: 'India' })
                });
                const data = await res.json();
                if (!data.error && data.data?.states) {
                    setRegions(data.data.states.map(s => ({ name: s.name })));
                    return;
                }
            }

            const res = await api.get('countries/regions', { params: { country_id: countryId } });
            if (res.data?.success) setRegions(res.data.data || []);
        } catch (e) {
            console.error('Error fetching regions:', e);
        } finally {
            setRegionsLoading(false);
        }
    };

    const fetchSelectedFields = async (moduleId, countryId, propertyTypeId, premisesTypeId, areaId, vehicleUsageId, vehicleCategoryId, region) => {
        try {
            const params = { module_id: moduleId };
            if (countryId) params.country_id = countryId;
            if (propertyTypeId) params.property_type_id = propertyTypeId;
            if (premisesTypeId) params.premises_type_id = premisesTypeId;
            if (areaId) params.area_id = areaId;
            if (vehicleUsageId) params.vehicle_usage_id = vehicleUsageId;
            if (vehicleCategoryId) params.vehicle_category_id = vehicleCategoryId;
            if (region) params.region = region;
            if (region && region !== 'All') params.region = region;

            const res = await api.get('company-modules/selected-fields', { params });
            return res.data?.data?.selected_field_ids;
        } catch (e) {
            console.error('[fetchSelectedFields] Error:', e);
            return null;
        }
    };

    const triggerFilePicker = (fieldKey) => {
        currentFileField.current = fieldKey;
        if (fileInputRef.current) fileInputRef.current.click();
    };

    const handleFileSelect = async (event) => {
        const file = event.target.files?.[0];
        const fieldKey = currentFileField.current;
        if (!file || !fieldKey) return;

        setUploadingField(fieldKey);
        const reader = new FileReader();
        reader.onloadend = async () => {
            const base64 = reader.result;
            try {
                const date = new Date();
                const formattedDate = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
                const randomNum = Math.floor(100 + Math.random() * 900);
                const customFileName = `VH ${formattedDate} - ${file.name} - ${randomNum}`;

                const result = await uploadFile({ name: customFileName, content: base64, moduleName: 'Vehicle' });
                if (result.success) {
                    setDynamicData(p => ({ ...p, [fieldKey]: result.path, [`${fieldKey}_name`]: customFileName }));
                }
            } catch (error) { console.error('File upload failed:', error); }
            finally {
                setUploadingField(null);
                if (fileInputRef.current) fileInputRef.current.value = '';
            }
        };
        reader.readAsDataURL(file);
    };

    const fetchModuleConfig = async () => {
        setLoading(true);
        try {
            const modRes = await api.get('module-master');
            const vehicleModule = (modRes.data?.data || []).find(m => (m.module_name || m.name || '').toLowerCase() === 'vehicle');

            if (!vehicleModule) return;

            const secRes = await api.get(`module-builder/${vehicleModule.module_id}/sections`);
            let sections = secRes.data?.data || [];

            const sectionsWithFields = await Promise.all(sections.map(async (sec) => {
                const fRes = await api.get(`module-builder/fields`, { params: { section_id: sec.id } });
                let fields = fRes.data?.data || [];
                return { ...sec, fields };
            }));

            const hasConditions = classification.country_id || classification.vehicle_usage_id || (classification.region && classification.region !== 'All');
            let filteredSections = [];

            if (hasConditions) {
                const selectedFieldIds = await fetchSelectedFields(
                    vehicleModule.module_id,
                    classification.country_id,
                    null, null, null,
                    classification.vehicle_usage_id,
                    null,
                    classification.region
                );
                if (!selectedFieldIds || selectedFieldIds.length === 0) {
                    filteredSections = [];
                    const requiredKeys = ['country_id', 'vehicle_usage_id'];
                    const selectedCount = requiredKeys.filter(k => classification[k] !== null && classification[k] !== '').length;

                    if (selectedCount >= 2) {
                        setAlertDialog({
                            visible: true,
                            title: 'Not Configured',
                            message: 'This combination is not configured.'
                        });
                    }
                } else {
                    filteredSections = sectionsWithFields.map(sec => ({
                        ...sec,
                        fields: sec.fields.filter(f => selectedFieldIds.some(sid => String(sid) === String(f.id) || String(sid) === String(f.field_key)))
                    })).filter(s => s.fields.length > 0);
                }
            } else {
                filteredSections = sectionsWithFields;
            }

            setModuleId(vehicleModule.module_id);
            setModuleStructure(filteredSections);

            // Fetch auto-generated IDs
            const autoFields = filteredSections.flatMap(s =>
                (s.fields || []).filter(f => f.field_type === 'auto_generated').map(f => ({ ...f, sectionId: s.id }))
            );
            if (autoFields.length > 0) {
                const results = {};
                for (const f of autoFields) {
                    const rawKey = f.field_key || `field_${f.id}`;
                    const compositeKey = `sec${f.sectionId}_${rawKey}`;
                    if (!dynamicData[compositeKey]) {
                        try {
                            const res = await api.get('module-builder/preview-id', {
                                params: { module_id: vehicleModule.module_id, field_key: f.field_key }
                            });
                            if (res.data?.success) results[compositeKey] = res.data.data;
                        } catch (e) { }
                    }
                }
                if (Object.keys(results).length > 0) setDynamicData(prev => ({ ...prev, ...results }));
            }
        } catch (error) {
            console.error('Error fetching module config:', error);
        } finally {
            setLoading(false);
            setInitializing(false);
        }
    };

    const handleNext = () => { if (step < totalSteps) setStep(step + 1); };
    const handleBack = () => { if (step > 1) setStep(step - 1); else onClose(); };

    const handleSaveForm = async () => {
        setSaving(true);
        try {
            const finalClassification = { ...classification };
            const realVehicleId = initialData?.vehicle_id; // real numeric DB id
            // Build payload: classification first, then dynamic fields
            // But ensure the real numeric vehicle_id always wins (not overwritten by a dynamic field named vehicle_id)
            const payload = { ...finalClassification, ...dynamicData };
            if (realVehicleId) payload.vehicle_id = realVehicleId;
            await onSave(payload);
        } catch (error) {
            console.error('Save error:', error);
        } finally {
            setSaving(false);
        }
    };

    const totalSteps = 1 + moduleStructure.length;
    const toggleMenu = (key, visible) => setMenus(prev => ({ ...prev, [key]: visible }));

    const renderDynamicSection = (stepIndex) => {
        const section = moduleStructure[stepIndex - 2];
        if (!section) return null;

        return (
            <View style={styles.stepContent}>
                <View style={styles.dynamicCard}>
                    <View style={styles.sectionHeaderCard}>
                        <Text style={styles.sectionHeaderTitle}>{section.name}</Text>
                    </View>
                    <View style={styles.cardBody}>
                        {Platform.OS === 'web' && (
                            <input type="file" ref={fileInputRef} style={{ display: 'none' }} onChange={handleFileSelect} />
                        )}
                        <View style={styles.fieldsGrid}>
                            {[...(section.fields || [])].filter(f => f.is_active !== 0).sort((a, b) => {
                                if (a.field_type === 'auto_generated' && b.field_type !== 'auto_generated') return -1;
                                if (a.field_type !== 'auto_generated' && b.field_type === 'auto_generated') return 1;
                                return 0;
                            }).map(field => {
                                const rawFieldKey = field.field_key || `field_${field.id}`;
                                const compositeKey = `sec${section.id}_${rawFieldKey}`;
                                const fieldName = field.label || field.field_name || field.name || 'Field';
                                const isDate = field.field_type === 'date' || rawFieldKey.toLowerCase().includes('date');

                                const isFile = ['file', 'file_upload', 'image', 'signature', 'pdf', 'file_pdf'].includes(field.field_type);
                                if (isFile) {
                                    const filePath = dynamicData[compositeKey];
                                    const fileName = dynamicData[`${compositeKey}_name`];
                                    const meta = field.meta_json ? (typeof field.meta_json === 'string' ? JSON.parse(field.meta_json) : field.meta_json) : null;
                                    const config = meta?.insurance_config || {};
                                    const hasAnyExtra = config.policyNo || config.coverageType || config.issueDate || config.startDate || config.endDate || config.expiry || config.reminder;

                                    return (
                                        <View key={field.id} style={[styles.dynamicField, hasAnyExtra && { width: '100%' }]}>
                                            <Text style={styles.inputLabel}>{fieldName}</Text>
                                            <View style={hasAnyExtra ? { flexDirection: 'row', gap: 16, alignItems: 'flex-start' } : null}>
                                                <View style={hasAnyExtra ? { flex: 1.5 } : null}>
                                                    {filePath ? (
                                                        <View style={styles.fileCard}>
                                                            <View style={{ flexDirection: 'row', alignItems: 'center', gap: 12 }}>
                                                                <MaterialCommunityIcons name="file-document-outline" size={24} color="#3b82f6" />
                                                                <View style={{ flex: 1 }}>
                                                                    <Text style={styles.fileName} numberOfLines={1}>{fileName}</Text>
                                                                    <Text style={styles.fileSub}>Uploaded Successfully</Text>
                                                                </View>
                                                                <TouchableOpacity onPress={() => triggerFilePicker(compositeKey)}>
                                                                    <MaterialCommunityIcons name="pencil-outline" size={20} color="#64748b" />
                                                                </TouchableOpacity>
                                                            </View>
                                                        </View>
                                                    ) : (
                                                        <TouchableOpacity style={[styles.uploadBox, uploadingField === compositeKey && { opacity: 0.6 }]} onPress={() => triggerFilePicker(compositeKey)}>
                                                            <MaterialCommunityIcons name="cloud-upload-outline" size={28} color="#94a3b8" />
                                                            <Text style={styles.uploadText}>Upload {fieldName}</Text>
                                                        </TouchableOpacity>
                                                    )}
                                                </View>
                                            </View>
                                        </View>
                                    );
                                }

                                return (
                                    <View key={field.id} style={styles.dynamicField}>
                                        <Text style={styles.inputLabel}>{fieldName}</Text>
                                        {(() => {
                                            const getFVal = (k) => dynamicData[k] || dynamicData[k + '_'] || '';
                                            const valToUse = getFVal(compositeKey) || getFVal(rawFieldKey);

                                            if (field.field_type === 'dropdown') {
                                                return (
                                                    <View>
                                                        <Menu visible={activeDynamicMenu === compositeKey} onDismiss={() => setActiveDynamicMenu(null)} anchor={
                                                            <TouchableOpacity onPress={() => setActiveDynamicMenu(compositeKey)} activeOpacity={0.7}>
                                                                <View pointerEvents="none">
                                                                    <TextInput mode="outlined" placeholder="Select..." value={valToUse} editable={false} style={styles.headerInput} outlineColor="#e2e8f0" activeOutlineColor="#3b82f6" theme={{ roundness: 8 }} right={<TextInput.Icon icon="chevron-down" />} />
                                                                </View>
                                                            </TouchableOpacity>
                                                        } contentStyle={styles.menuContent}>
                                                            <ScrollView style={{ maxHeight: 300, width: 260 }}>
                                                                {(field.options || []).map((opt, idx) => (
                                                                    <Menu.Item
                                                                        key={idx}
                                                                        onPress={() => {
                                                                            setDynamicData(p => ({ ...p, [compositeKey]: opt.option_value || opt.value || opt.option_label }));
                                                                            setActiveDynamicMenu(null);
                                                                        }}
                                                                        title={opt.option_label || opt.label}
                                                                        titleStyle={[styles.menuItemLabel, valToUse === (opt.option_value || opt.value || opt.option_label) && styles.menuItemLabelSelected]}
                                                                        style={[styles.menuItem, valToUse === (opt.option_value || opt.value || opt.option_label) && styles.menuItemSelected]}
                                                                    />
                                                                ))}
                                                            </ScrollView>
                                                        </Menu>
                                                    </View>
                                                );
                                            }

                                            if (field.field_type === 'radio' || field.field_type === 'boolean') {
                                                return (
                                                    <RadioButton.Group onValueChange={val => setDynamicData(p => ({ ...p, [compositeKey]: val }))} value={valToUse}>
                                                        <View style={{ flexDirection: 'row', alignItems: 'center', marginTop: 8 }}>
                                                            <View style={{ flexDirection: 'row', alignItems: 'center', marginRight: 20 }}>
                                                                <RadioButton value="Yes" color="#673ab7" />
                                                                <Text style={{ color: '#1e293b' }}>Yes</Text>
                                                            </View>
                                                            <View style={{ flexDirection: 'row', alignItems: 'center' }}>
                                                                <RadioButton value="No" color="#673ab7" />
                                                                <Text style={{ color: '#1e293b' }}>No</Text>
                                                            </View>
                                                        </View>
                                                    </RadioButton.Group>
                                                );
                                            }

                                            return (
                                                <TextInput
                                                    mode="outlined"
                                                    placeholder={field.field_type === 'auto_generated' ? '[SYSTEM GENERATED]' : `Enter ${fieldName.toLowerCase()}`}
                                                    value={valToUse}
                                                    onChangeText={(text) => setDynamicData(p => ({ ...p, [compositeKey]: text }))}
                                                    editable={field.field_type !== 'auto_generated'}
                                                    style={[styles.headerInput, field.field_type === 'auto_generated' && { backgroundColor: '#f8fafc' }]}
                                                    outlineColor="#e2e8f0"
                                                    activeOutlineColor="#673ab7"
                                                    theme={{ roundness: 8 }}
                                                    right={field.field_type === 'auto_generated' ? (
                                                        <TextInput.Icon icon="lock" color="#94a3b8" />
                                                    ) : isDate ? (
                                                        <TextInput.Icon icon="calendar" color="#94a3b8" />
                                                    ) : (
                                                        <TextInput.Icon icon="pencil-outline" color="#94a3b8" />
                                                    )}
                                                    render={isDate ? renderDateInput(compositeKey, valToUse, (val) => setDynamicData(p => ({ ...p, [compositeKey]: val }))) : undefined}
                                                />
                                            );
                                        })()}
                                    </View>
                                );
                            })}
                        </View>
                    </View>
                </View>
            </View>
        );
    };

    return (
        <Portal>
            <Modal visible={visible} onDismiss={onClose} contentContainerStyle={styles.container}>
                <View style={styles.modalHeader}>
                    <View>
                        <Text style={styles.modalTitle}>Vehicle</Text>
                        <Text style={styles.modalSub}>
                            {initialData ? 'Edit vehicle' : 'Add new'} • Step {step}
                        </Text>
                    </View>
                    <TouchableOpacity onPress={onClose}><MaterialCommunityIcons name="close" size={24} color="#64748b" /></TouchableOpacity>
                </View>

                {/* Progress Stepper */}
                {initializing ? (
                    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}><ActivityIndicator size="large" color="#3b82f6" /></View>
                ) : (
                    <>
                        <ScrollView style={styles.scrollArea} contentContainerStyle={styles.scrollContent}>
                            {step === 1 && (
                                <View style={styles.stepOneContainer}>
                                    <View style={styles.stepperContainer}>
                                        {(() => {
                                            const getStepperItems = (current, total) => {
                                                if (total <= 6) return Array.from({ length: total }, (_, i) => i + 1);
                                                if (current <= 4) return [1, 2, 3, 4, 5, '...', total];
                                                if (current >= total - 3) return [1, '...', total - 4, total - 3, total - 2, total - 1, total];
                                                return [1, '...', current - 1, current, current + 1, '...', total];
                                            };
                                            const items = getStepperItems(step, totalSteps);

                                            return items.map((item, index) => {
                                                const isEllipsis = item === '...';

                                                // Resolve logical step number for line coloring
                                                const prevNum = index > 0 ? (items[index - 1] === '...' ? items[index - 2] : items[index - 1]) : 0;
                                                const currentLogicalNum = isEllipsis ? prevNum : item;

                                                const isCompleted = step > currentLogicalNum;
                                                const isActive = step === item;

                                                const label = isEllipsis ? ' ' : (item === 1 ? 'Basic Info' : (moduleStructure[item - 2]?.name || `Section ${item}`));

                                                return (
                                                    <React.Fragment key={isEllipsis ? `ellipsis-${index}` : `step-${item}`}>
                                                        <View style={[styles.stepItem, isEllipsis && { marginHorizontal: 15 }]}>
                                                            <View style={[styles.stepCircle, !isEllipsis && (isActive || isCompleted) && styles.stepCircleActive, isEllipsis && { backgroundColor: 'transparent' }]}>
                                                                {isEllipsis ? (
                                                                    <Text style={{ fontSize: 20, color: '#94a3b8', fontWeight: 'bold' }}>...</Text>
                                                                ) : isCompleted ? (
                                                                    <MaterialCommunityIcons name="check" size={18} color="white" />
                                                                ) : (
                                                                    <Text style={[styles.stepNumber, (isActive || isCompleted) && styles.stepNumberActive]}>{item}</Text>
                                                                )}
                                                            </View>
                                                            <Text style={styles.stepLabel} numberOfLines={1}>{label}</Text>
                                                        </View>
                                                        {index < items.length - 1 && <View style={[styles.stepLine, isCompleted && styles.stepLineActive]} />}
                                                    </React.Fragment>
                                                );
                                            });
                                        })()}
                                    </View>

                                    <Card style={styles.sectionCard}>
                                        <View style={styles.sectionHeader}><Text style={styles.sectionTitle}>{step}. Basic Information</Text></View>
                                        <View style={styles.headerForm}>
                                            <View style={styles.headerFormGrid}>
                                                <View style={styles.headerFieldSmall}>
                                                    <Text style={styles.headerLabel}>Company</Text>
                                                    <Menu
                                                        visible={menus.company}
                                                        onDismiss={() => toggleMenu('company', false)}
                                                        anchor={
                                                            <TouchableOpacity onPress={() => toggleMenu('company', true)}>
                                                                <View pointerEvents="none">
                                                                    <TextInput
                                                                        mode="outlined"
                                                                        value={classification.company_name || ''}
                                                                        editable={false}
                                                                        style={styles.headerInput}
                                                                        placeholder="Select Company"
                                                                        right={<TextInput.Icon icon="chevron-down" size={18} color="#64748b" />}
                                                                        outlineColor="#e2e8f0"
                                                                        activeOutlineColor="#673ab7"
                                                                        theme={{ roundness: 8, colors: { text: '#1e293b' } }}
                                                                    />
                                                                </View>
                                                            </TouchableOpacity>
                                                        }
                                                        contentStyle={styles.menuContent}
                                                    >
                                                        <ScrollView style={{ maxHeight: 300, width: 260 }}>
                                                            {companies.map(c => (
                                                                <Menu.Item
                                                                    key={c.id}
                                                                    onPress={() => {
                                                                        toggleMenu('company', false);
                                                                        setClassification(p => ({ ...p, company_id: c.id, company_name: c.company_name || c.name }));
                                                                    }}
                                                                    title={c.company_name || c.name}
                                                                    titleStyle={[styles.menuItemLabel, classification.company_id === c.id && styles.menuItemLabelSelected]}
                                                                    style={[styles.menuItem, classification.company_id === c.id && styles.menuItemSelected]}
                                                                />
                                                            ))}
                                                        </ScrollView>
                                                    </Menu>
                                                </View>

                                                <View style={styles.headerFieldSmall}>
                                                    <Text style={styles.headerLabel}>Country</Text>
                                                    <Menu
                                                        visible={menus.country}
                                                        onDismiss={() => toggleMenu('country', false)}
                                                        anchor={
                                                            <TouchableOpacity onPress={() => toggleMenu('country', true)}>
                                                                <View pointerEvents="none">
                                                                    <TextInput
                                                                        mode="outlined"
                                                                        value={classification.country_name || ''}
                                                                        editable={false}
                                                                        style={styles.headerInput}
                                                                        placeholder="Select Country"
                                                                        right={<TextInput.Icon icon="chevron-down" size={18} color="#64748b" />}
                                                                        outlineColor="#e2e8f0"
                                                                        activeOutlineColor="#673ab7"
                                                                        theme={{ roundness: 8, colors: { text: '#1e293b' } }}
                                                                    />
                                                                </View>
                                                            </TouchableOpacity>
                                                        }
                                                        contentStyle={styles.menuContent}
                                                    >
                                                        <ScrollView style={{ maxHeight: 300, width: 260 }}>
                                                            {countries.map(c => (
                                                                <Menu.Item
                                                                    key={c.id}
                                                                    onPress={() => {
                                                                        toggleMenu('country', false);
                                                                        setClassification(p => ({ ...p, country_id: c.id, country_name: c.country_name || c.name, region: '' }));
                                                                    }}
                                                                    title={c.country_name || c.name}
                                                                    titleStyle={[styles.menuItemLabel, classification.country_id === c.id && styles.menuItemLabelSelected]}
                                                                    style={[styles.menuItem, classification.country_id === c.id && styles.menuItemSelected]}
                                                                />
                                                            ))}
                                                        </ScrollView>
                                                    </Menu>
                                                </View>

                                                <View style={styles.headerFieldSmall}>
                                                    <Text style={styles.headerLabel}>Region</Text>
                                                    <Menu
                                                        visible={menus.region}
                                                        onDismiss={() => toggleMenu('region', false)}
                                                        anchor={
                                                            <TouchableOpacity
                                                                onPress={() => toggleMenu('region', true)}
                                                                disabled={!classification.country_id || regionsLoading}
                                                            >
                                                                <View pointerEvents="none">
                                                                    <TextInput
                                                                        mode="outlined"
                                                                        placeholder={classification.country_id ? (regionsLoading ? "Loading..." : "Select Region") : "Select Country first"}
                                                                        value={classification.region || ''}
                                                                        editable={false}
                                                                        style={[styles.headerInput, (!classification.country_id || regionsLoading) && { backgroundColor: '#f8fafc' }]}
                                                                        right={<TextInput.Icon icon={regionsLoading ? "loading" : "chevron-down"} size={18} color="#64748b" />}
                                                                        outlineColor="#e2e8f0"
                                                                        activeOutlineColor="#673ab7"
                                                                        theme={{ roundness: 8, colors: { text: '#1e293b' } }}
                                                                    />
                                                                </View>
                                                            </TouchableOpacity>
                                                        }
                                                        contentStyle={styles.menuContent}
                                                    >
                                                        <ScrollView style={{ maxHeight: 300, width: 260 }}>
                                                            {regions.length > 0 ? regions.map((r, i) => (
                                                                <Menu.Item
                                                                    key={i}
                                                                    onPress={() => {
                                                                        toggleMenu('region', false);
                                                                        setClassification(p => ({ ...p, region: r.name }));
                                                                    }}
                                                                    title={r.name}
                                                                    titleStyle={[styles.menuItemLabel, classification.region === r.name && styles.menuItemLabelSelected]}
                                                                    style={[styles.menuItem, classification.region === r.name && styles.menuItemSelected]}
                                                                />
                                                            )) : <Menu.Item title="No regions found" disabled titleStyle={styles.menuItemLabel} />}
                                                        </ScrollView>
                                                    </Menu>
                                                </View>

                                                <View style={styles.headerFieldSmall}>
                                                    <Text style={styles.headerLabel}>Usage</Text>
                                                    <Menu
                                                        visible={menus.premisesType}
                                                        onDismiss={() => toggleMenu('premisesType', false)}
                                                        anchor={
                                                            <TouchableOpacity onPress={() => toggleMenu('premisesType', true)}>
                                                                <View pointerEvents="none">
                                                                    <TextInput
                                                                        mode="outlined"
                                                                        value={classification.premises_type_name || ''}
                                                                        editable={false}
                                                                        style={styles.headerInput}
                                                                        placeholder="Select Usage"
                                                                        right={<TextInput.Icon icon="chevron-down" size={18} color="#64748b" />}
                                                                        outlineColor="#e2e8f0"
                                                                        activeOutlineColor="#673ab7"
                                                                        theme={{ roundness: 8, colors: { text: '#1e293b' } }}
                                                                    />
                                                                </View>
                                                            </TouchableOpacity>
                                                        }
                                                        contentStyle={styles.menuContent}
                                                    >
                                                        <ScrollView style={{ maxHeight: 300, width: 264 }}>
                                                            {vehicleUsages.map(u => (
                                                                <Menu.Item
                                                                    key={u.id}
                                                                    onPress={() => {
                                                                        toggleMenu('premisesType', false);
                                                                        setClassification(p => ({ ...p, vehicle_usage_id: u.id, premises_type_name: u.name }));
                                                                    }}
                                                                    title={u.name}
                                                                    titleStyle={[styles.menuItemLabel, classification.vehicle_usage_id === u.id && styles.menuItemLabelSelected]}
                                                                    style={[styles.menuItem, classification.vehicle_usage_id === u.id && styles.menuItemSelected]}
                                                                />
                                                            ))}
                                                        </ScrollView>
                                                    </Menu>
                                                </View>
                                            </View>

                                            <View style={styles.statusSectionContainer}>
                                                <Text style={styles.headerLabel}>Status</Text>
                                                <Switch value={classification.status === 'Active'} onValueChange={(val) => setClassification(p => ({ ...p, status: val ? 'Active' : 'Inactive' }))} color="rgb(103, 58, 183)" />
                                            </View>
                                        </View>
                                    </Card>
                                </View>
                            )}
                            {step >= 2 && renderDynamicSection(step)}
                        </ScrollView>
                        <View style={styles.modalFooter}>
                            <TouchableOpacity onPress={step === 1 ? onClose : handleBack} style={[styles.footerBtn, { backgroundColor: '#fff', borderWidth: 1, borderColor: '#e2e8f0' }]}>
                                <Text style={[styles.footerBtnText, { color: '#64748b' }]}>{step === 1 ? 'Cancel' : 'Back'}</Text>
                            </TouchableOpacity>
                            <TouchableOpacity onPress={step < totalSteps ? handleNext : handleSaveForm} style={[styles.footerBtn, { backgroundColor: '#673ab7' }]} disabled={loading || saving}>
                                {loading || saving ? (
                                    <ActivityIndicator color="white" size="small" />
                                ) : (
                                    <View style={{ flexDirection: 'row', alignItems: 'center' }}>
                                        <Text style={[styles.footerBtnText, { color: 'white' }]}>{step < totalSteps ? 'Next Step' : 'Save'}</Text>
                                        {step < totalSteps && <MaterialCommunityIcons name="arrow-right" size={18} color="white" style={{ marginLeft: 8 }} />}
                                    </View>
                                )}
                            </TouchableOpacity>
                        </View>
                    </>
                )}
            </Modal>
            <AlertDialog visible={alertDialog.visible} onDismiss={() => setAlertDialog(p => ({ ...p, visible: false }))} title={alertDialog.title} message={alertDialog.message} />
        </Portal>
    );
};

const styles = StyleSheet.create({
    container: { backgroundColor: 'white', alignSelf: 'center', width: '90%', maxWidth: 1100, maxHeight: '95%', borderRadius: 12 },
    modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 20, borderBottomWidth: 1, borderBottomColor: '#f1f5f9' },
    modalTitle: { fontSize: 20, fontWeight: '800', color: '#1e293b' },
    modalSub: { fontSize: 13, color: '#64748b', marginTop: 2 },
    modalContent: { flex: 1, backgroundColor: '#f8fafc' },
    scrollArea: { flex: 1 },
    scrollContent: { flexGrow: 1, paddingBottom: 20 },
    stepperContainer: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#fff', borderBottomWidth: 1, borderBottomColor: '#f1f5f9', marginBottom: 10, paddingVertical: 20 },
    stepItem: { alignItems: 'center', width: 90, marginHorizontal: 0 },
    stepCircle: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#e2e8f0', justifyContent: 'center', alignItems: 'center', marginBottom: 6 },
    stepCircleActive: { backgroundColor: '#673ab7' },
    stepNumber: { fontSize: 16, fontWeight: '700', color: '#64748b' },
    stepNumberActive: { color: '#fff' },
    stepLabel: { fontSize: 11, color: '#64748b', fontWeight: '600', textAlign: 'center' },
    stepLine: { width: 30, height: 2, backgroundColor: '#e2e8f0', marginTop: -25 },
    stepLineActive: { backgroundColor: '#673ab7' },
    stepOneContainer: { flex: 1 },
    sectionCard: { marginHorizontal: 20, marginTop: 10, borderRadius: 8, elevation: 0, backgroundColor: '#fff', borderWidth: 1, borderColor: '#e2e8f0', overflow: 'hidden' },
    sectionHeader: { backgroundColor: '#673ab7', paddingVertical: 10, paddingHorizontal: 16 },
    sectionTitle: { color: '#fff', fontSize: 16, fontWeight: '700' },
    headerForm: { padding: 20 },
    headerFormGrid: { flexDirection: 'row', flexWrap: 'wrap', marginHorizontal: -8 },
    headerFieldSmall: { width: '25%', paddingHorizontal: 8, marginBottom: 16 },
    headerLabel: { fontSize: 13, fontWeight: '700', color: '#334155', marginBottom: 8 },
    headerInput: { height: 40, backgroundColor: '#fff', fontSize: 13 },
    modalFooter: { flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: 20, paddingVertical: 16, borderTopWidth: 1, borderTopColor: '#f1f5f9', backgroundColor: '#fff' },
    footerBtn: { borderRadius: 8, paddingVertical: 10, paddingHorizontal: 24, minWidth: 120, alignItems: 'center', justifyContent: 'center' },
    footerBtnText: { fontSize: 14, fontWeight: '700' },
    moduleChipText: { fontSize: 12, fontWeight: '700', color: '#1d4ed8' },
    stepContent: { padding: 24 },
    dynamicCard: { backgroundColor: 'white', borderRadius: 12, borderWidth: 1, borderColor: '#e2e8f0', overflow: 'hidden' },
    sectionHeaderCard: { backgroundColor: '#673ab7', paddingVertical: 16, paddingHorizontal: 24 },
    sectionHeaderTitle: { fontWeight: '700', color: '#ffffff', fontSize: 18 },
    cardBody: { padding: 24 },
    fieldsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 16 },
    dynamicField: { width: '48%', marginBottom: 16 },
    fileCard: { backgroundColor: '#f8fafc', borderRadius: 12, padding: 12, borderWidth: 1, borderColor: '#e2e8f0', height: 60, justifyContent: 'center' },
    fileName: { fontSize: 13, fontWeight: '700', color: '#1e293b' },
    fileSub: { fontSize: 11, color: '#64748b' },
    uploadBox: { height: 80, borderRadius: 12, borderWidth: 2, borderColor: '#e2e8f0', borderStyle: 'dashed', justifyContent: 'center', alignItems: 'center', backgroundColor: '#f8fafc' },
    uploadText: { marginTop: 8, fontSize: 13, color: '#475569', fontWeight: '700' },
    modalFooter: { flexDirection: 'row', justifyContent: 'space-between', padding: 16, borderTopWidth: 1, borderTopColor: '#f1f5f9', backgroundColor: '#ffffff' },
    cancelBtn: { paddingHorizontal: 16, paddingVertical: 10, borderRadius: 8, borderWidth: 1, borderColor: '#e2e8f0' },
    cancelBtnText: { color: '#64748b', fontWeight: '700' },
    nextBtn: { backgroundColor: '#3b82f6', paddingHorizontal: 20, paddingVertical: 10, borderRadius: 8 },
    nextBtnText: { color: 'white', fontWeight: '700' },
    menuContent: {
        backgroundColor: 'white',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#e2e8f0',
        minWidth: 200,
        paddingVertical: 6,
        marginTop: 45, // Push menu below the input and label
        // Modern shadow
        shadowColor: '#1e293b',
        shadowOffset: { width: 0, height: 12 },
        shadowOpacity: 0.12,
        shadowRadius: 24,
        elevation: 8,
    },
    menuItem: {
        height: 44,
        paddingHorizontal: 8,
        justifyContent: 'center',
    },
    menuItemSelected: {
        backgroundColor: '#f5f3ff', // Light purple tint for selected
    },
    menuItemLabel: {
        fontSize: 13,
        color: '#475569',
        fontWeight: '500',
    },
    menuItemLabelSelected: {
        color: '#673ab7',
        fontWeight: '700',
    }
});

export default VehicleWizardModal;
